# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('opening', models.FloatField()),
                ('closing', models.FloatField()),
            ],
        ),
    ]
